### ISSUE TITLE
Clean up the staging builds installation directory

### ISSUE THREAD

**Issue by sbose78** [redhat-appstudio/infra-deployments#20]
https://github.com/redhat-appstudio/infra-deployments/pull/19#pullrequestreview-813815314

**Comment by sbose78** [comment]
* Could you also move `hack` out of `components` into a more top-level `hack` ?

**Comment by jduimovich** [comment]
We'll need a naming conventions for pipelines, to help map source repo type (node.js, java, quarkus) and  build type (docker, maven, gradle)  to pipeline names.  I can rename but eventually the xyz-build pipelines will be app-studio-xyz because it will produce a build and scans, licensed checks as an all in one solution

**Comment by sbose78** [comment]
Agreed.
The app-studio- prefix is fine, my only suggestion is we keep `-dockerfile-builder-` or something similar somewhere :) Also, it doesn't have to be inside `experimental-`.

**Comment by jduimovich** [comment]
For now, I moved it to docker-build since that is all it does.
I have refactored and removed experimental-.

We can work on a app-studio-default pipeline as we flesh out the tasks for the scanners, linters

The scripts will be moved to hack/build. so that each component can have its own hack scripts. 
The script for using the build service for a docker build will be at hack/build/build.sh <url>
